spring:
  config:
    on-profile:
      - local
      -
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 146ca76e1e1e461ed97f
            clientSecret: a6a9d2814e6bd02013d2434366a8892f96ee5f74
